"use client";
import { useEffect, useMemo, useState } from "react";
import Atmosphere from "./Atmosphere";
import StarMap from "./StarMap";
import Timeline from "./Timeline";
import { daysSince, endings, formatDate, initialEncounter, questions, results, type Accuracy } from "../lib/encounter";

type Scene = "opening"|"stars"|"pair"|"scan"|"name"|"questions"|"analysis"|"report"|"error"|"memory"|"date"|"timeline"|"days"|"conversion"|"questionParallel"|"missed"|"parallel"|"ending"|"choice"|"confirmed"|"generating"|"record";

export default function EncounterExperience() {
  const [scene,setScene]=useState<Scene>("opening"); const [state,setState]=useState(initialEncounter);
  const [question,setQuestion]=useState(0); const [progress,setProgress]=useState(0); const [year,setYear]=useState("2024"); const [egg,setEgg]=useState(false);
  const result=useMemo(()=>results(state),[state]); const days=daysSince(state.meetingDate); const today=new Date().toISOString().slice(0,10);
  const dark=["missed","parallel","ending"].includes(scene); const warm=["timeline","days","conversion","choice","confirmed","generating","record"].includes(scene);
  useEffect(()=>{ let t:number|undefined; if(scene==="scan"){setProgress(0);let p=0;t=window.setInterval(()=>{p+=p<27?9:p<68?13:p<99?10:0;setProgress(Math.min(99,p));if(p>=99)window.clearInterval(t);},260)} if(scene==="analysis"){setProgress(0);let p=0;t=window.setInterval(()=>{p+=8;setProgress(Math.min(100,p));if(p>=100){window.clearInterval(t);window.setTimeout(()=>setScene("report"),450)}},100)} if(scene==="timeline")t=window.setTimeout(()=>setScene("days"),4200); if(scene==="missed")t=window.setTimeout(()=>setScene("parallel"),4300); if(scene==="generating")t=window.setTimeout(()=>setScene("record"),2800); if(scene==="record"){setEgg(false);t=window.setTimeout(()=>setEgg(true),8000)} return()=>{if(t)window.clearInterval(t)}},[scene]);
  const choose=(i:number)=>{const answers=[...state.answers];answers[question]=i;setState({...state,answers});if(question<3)setQuestion(question+1);else setScene("analysis")};
  const setAccuracy=(a:Accuracy)=>{setState({...state,meetingAccuracy:a});setScene("date")};
  const finishDate=()=>{let date=state.meetingDate;if(state.meetingAccuracy!=="exact"){date=`${year}-${state.meetingAccuracy==="unknown"?"07-01":"09-01"}`;setState(s=>({...s,meetingDate:date,meetingDateRange:`${year} 年${s.meetingAccuracy==="unknown"?"左右":"秋天前后"}`}))}setScene("timeline")};
  const idx=({opening:1,stars:2,pair:3,scan:4,name:5,questions:6,analysis:10,report:11,error:12,memory:13,date:14,timeline:15,days:16,conversion:17,questionParallel:18,missed:19,parallel:20,ending:21,choice:22,confirmed:22,generating:23,record:24} as Record<Scene,number>)[scene];
  const basic=(children:React.ReactNode, cls="")=><section className={`scene is-ready ${cls}`}><div className="scene-index"><span>{String(idx).padStart(2,"0")}</span><i/></div>{children}</section>;
  return <main className={`experience ${dark?"is-parallel":""} ${warm?"is-warm":""}`}>
    <Atmosphere intensity={dark?"parallel":warm?"warm":scene==="stars"?"stars":"quiet"}/>
    {scene==="opening"&&basic(<button className="screen-tap" onClick={()=>setScene("stars")}><p className="eyebrow">QIXI · ENCOUNTER EXPERIMENT</p><h1>现在，<br/>世界上有 <em>80</em> 多亿人。</h1><span className="tap-hint">轻触屏幕继续</span></button>)}
    {scene==="stars"&&basic(<button className="screen-tap" onClick={()=>setScene("pair")}><p className="eyebrow">8,000,000,000+ POSSIBILITIES</p><h1>绝大多数人，<br/>你一辈子都不会遇见。</h1><span className="tap-hint">让星光散开</span></button>)}
    {scene==="pair"&&basic(<div className="center-stack"><p className="story-copy">但今晚，<br/>你点进来了。</p><div className="pair-orbit"><span><i/>CC</span><b/><span><i/>YOU</span></div><p className="story-copy small">所以我有点好奇——<br/>我们为什么会遇见？</p><button className="primary" onClick={()=>setScene("scan")}>开始实验</button></div>)}
    {scene==="scan"&&basic(<div className="lab-panel"><p className="eyebrow">RELATIONSHIP LAB</p><p>正在识别访问者……</p><div className="scan-ring" style={{"--progress":`${progress*3.6}deg`} as React.CSSProperties}><span>{progress}%</span></div>{progress>=99&&<><strong className="error-text">IDENTIFICATION FAILED</strong><p>我还不知道你是谁。</p><button className="ghost" onClick={()=>setScene("name")}>告诉我</button></>}</div>)}
    {scene==="name"&&basic(<form className="center-stack form" onSubmit={e=>{e.preventDefault();if(state.nickname.trim())setScene("questions")}}><p className="eyebrow">IDENTIFICATION · 01</p><label htmlFor="nickname">平时别人怎么叫你？</label><input id="nickname" maxLength={12} placeholder="你的昵称" value={state.nickname} onChange={e=>setState({...state,nickname:e.target.value})}/><p className="microcopy">只会保存在你的设备上</p><button className="primary" disabled={!state.nickname.trim()}>现在认识了</button></form>)}
    {scene==="questions"&&basic(<div className="question-card"><p className="eyebrow">{questions[question].kicker}</p><h2>{questions[question].lines.map((x,i)=><span key={i}>{x}</span>)}</h2><div className="options">{questions[question].options.map((x,i)=><button key={x} onClick={()=>choose(i)}>{x}</button>)}</div><div className="dots">{questions.map((_,i)=><i key={i} className={i===question?"active":""}/>)}</div></div>)}
    {scene==="analysis"&&basic(<div className="analysis"><p className="eyebrow">ANALYZING RELATIONSHIP</p><div className="analysis-bars">{Object.entries({默契度:result.scores.chemistry,废话浓度:result.scores.chatter,失联风险:result.scores.lostRisk,一起搞事情概率:result.scores.adventure,关系稳定性:result.scores.stability}).map(([k,v],i)=><div key={k} style={{transitionDelay:`${i*.1}s`}}><span>{k}<b>{progress>=100?v:Math.round(v*progress/100)}%</b></span><i><em style={{width:`${progress>=100?v:v*progress/100}%`}}/></i></div>)}</div><p className="microcopy">正在比对你们之间的微小证据</p></div>)}
    {scene==="report"&&basic(<div className="report"><p className="eyebrow">RELATIONSHIP REPORT · 2026</p><h2>CC <small>×</small> {state.nickname}</h2><p>当前关系类型</p><strong>{result.label}</strong><div className="radar"><i/><i/><i/><i/><i/><span>{result.scores.chemistry}%</span></div><button className="primary" onClick={()=>setScene("error")}>查看完整报告</button></div>)}
    {scene==="error"&&basic(<button className="screen-tap glitch" onClick={()=>setScene("memory")}><p className="error-big">ERROR</p><h2>等一下。</h2><p className="story-copy small">其实我真正想算的，<br/>不是这些。</p><span className="tap-hint">点击继续</span></button>)}
    {scene==="memory"&&basic(<div className="question-card"><p className="story-copy align-left"><b>{state.nickname}。</b><br/><br/>你还记得，<br/>我们什么时候认识的吗？</p><div className="options"><button onClick={()=>setAccuracy("exact")}>我记得</button><button onClick={()=>setAccuracy("approx")}>只记得大概</button><button onClick={()=>setAccuracy("unknown")}>完全不记得</button></div></div>)}
    {scene==="date"&&basic(<div className="center-stack form date-form"><p className="eyebrow">MEETING DATE</p>{state.meetingAccuracy==="exact"?<><label htmlFor="date">那一天是？</label><input id="date" type="date" max={today} value={state.meetingDate} onInput={e=>setState({...state,meetingDate:(e.currentTarget as HTMLInputElement).value})} onChange={e=>setState({...state,meetingDate:e.target.value})}/><button className="primary" disabled={!state.meetingDate} onClick={finishDate}>确定</button></>:<><p className="story-copy small">{state.meetingAccuracy==="unknown"?"其实很正常。很少有人在认识一个人的第一天，就知道这个人以后可能会重要。":"没关系，时间不一定需要精确到某一天。"}</p><label htmlFor="year">至少，选一个大概年份</label><select id="year" value={year} onChange={e=>setYear(e.target.value)}>{Array.from({length:15},(_,i)=>String(new Date().getFullYear()-i)).map(y=><option key={y}>{y}</option>)}</select><button className="primary" onClick={finishDate}>就从这里开始</button></>}</div>)}
    {scene==="timeline"&&basic(<div className="timeline-screen"><p className="eyebrow">TRACING BOTH LIVES</p><Timeline name={state.nickname}/><p className="microcopy">两条时间线正在靠近</p></div>)}
    {scene==="days"&&basic(<button className="screen-tap" onClick={()=>setScene("conversion")}><p className="story-copy small">这一天，<br/>我们认识了。</p><div className="days-number">{days.toLocaleString("zh-CN")}<small>天</small></div><p className="story-copy small">今天，<br/>是我们认识的第 {days.toLocaleString("zh-CN")} 天。</p><span className="tap-hint">继续换算时间</span></button>)}
    {scene==="conversion"&&basic(<div className="conversion"><p className="eyebrow">TIME, IN OTHER UNITS</p><h2>{days.toLocaleString()} 天</h2><div><p><i>◷</i><span>约 {(days*24).toLocaleString()} 个小时</span></p><p><i>◎</i><span>地球已经绕太阳约 {(days/365.2422).toFixed(2)} 圈</span></p><p><i>⌁</i><span>共同经过约 {Math.max(1,Math.round(days/91.31))} 个季节</span></p></div><blockquote>“原来认识一个人，<br/>也是一种时间单位。”</blockquote><button className="ghost" onClick={()=>setScene("questionParallel")}>继续</button></div>)}
    {scene==="questionParallel"&&basic(<div className="center-stack"><p className="story-copy">不过我突然想到一个问题。</p><h2>如果那一天，<br/>我们没有遇见呢？</h2><button className="primary" onClick={()=>setScene("missed")}>看看另一个世界</button></div>)}
    {scene==="missed"&&basic(<div className="timeline-screen"><p className="eyebrow">ALTERNATE TIMELINE</p><Timeline name={state.nickname} missed/><p className="microcopy">时间仍然向前</p></div>)}
    {scene==="parallel"&&basic(<div className="parallel-copy"><p>什么都不会发生。</p><p>你还是会继续生活。<br/>我也是。</p><p>我们会认识另外的人，<br/>去另外的地方，<br/>过另一种生活。</p><strong>只是彼此的世界里，<br/>会少掉一个人。</strong><button className="ghost" onClick={()=>setScene("ending")}>我知道了</button></div>)}
    {scene==="ending"&&basic(<div className="ending"><p className="eyebrow">ABOUT US · {result.ending}</p>{endings[result.ending].map((x,i)=><p key={i}>{x}</p>)}<button className="ghost" onClick={()=>setScene("choice")}>继续</button></div>)}
    {scene==="choice"&&basic(<div className="question-card"><p className="story-copy">如果把时间拨回<br/>我们认识之前——</p><h2>你还愿意认识我吗？</h2><div className="options"><button className="selected" onClick={()=>{setState({...state,finalChoice:"yes"});setScene("confirmed")}}>愿意</button><button onClick={()=>{setState({...state,finalChoice:"maybe"});setScene("confirmed")}}>再想想</button></div></div>)}
    {scene==="confirmed"&&basic(<div className="center-stack reunion"><div className="pair-orbit is-reunited"><span><i/>CC</span><b/><span><i/>{state.nickname}</span></div><h2>{state.finalChoice==="yes"?"已确认。":"可以。"}</h2><p className="story-copy small">{state.finalChoice==="yes"?"那我们把这条时间线，再往后写一点。":"那这个世界，先别走散。"}</p><button className="primary" onClick={()=>setScene("generating")}>生成相遇记录</button></div>)}
    {scene==="generating"&&basic(<div className="generating"><p className="eyebrow">GENERATING</p><h2>ENCOUNTER RECORD</h2><StarMap seed={result.seed} compact/><p>正在把你们的时间写进星图</p></div>)}
    {scene==="record"&&basic(<div className="record-wrap"><div className="record" id="encounter-record"><p className="eyebrow">ENCOUNTER RECORD · QIXI 2026</p><h2>CC <small>×</small> {state.nickname}</h2><div className="record-days">{days.toLocaleString()} <span>DAYS</span></div><p className="record-date">{formatDate(state.meetingDate)} — {formatDate(today)}</p><StarMap seed={result.seed}/><strong>{result.label}</strong><blockquote>在很多种可能里，<br/>我们刚好活在认识彼此的这一种。</blockquote>{egg&&<p className="easter-egg">P.S. 七夕快乐。</p>}</div><p className="screenshot-tip">长按或截图，保存这张相遇记录</p><button className="ghost" onClick={()=>setScene("timeline")}>再看看我们的时间线</button></div>)}
  </main>;
}
